Category.create(id: 1, name: '介護')
Category.create(id: 2, name: '心理')
Category.create(id: 3, name: 'ペット')
Category.create(id: 4, name: '食')
Category.create(id: 5, name: 'ビジネス')
Category.create(id: 6, name: '保育')
Category.create(id: 7, name: 'ヘルスケア')
Category.create(id: 8, name: '美容')
Category.create(id: 9, name: 'パソコン')
Category.create(id: 10, name: 'IT・Web')
Category.create(id: 11, name: 'コンサル系')
Category.create(id: 12, name: '医療')
Category.create(id: 13, name: '会計')
Category.create(id: 14, name: '不動産')
Category.create(id: 15, name: '公務員')
Category.create(id: 16, name: '電気')
Category.create(id: 17, name: 'その他')
Lounge.create(category_id: 1)
Lounge.create(category_id: 2)
Lounge.create(category_id: 3)
Lounge.create(category_id: 4)
Lounge.create(category_id: 5)
Lounge.create(category_id: 6)
Lounge.create(category_id: 7)
Lounge.create(category_id: 8)
Lounge.create(category_id: 9)
Lounge.create(category_id: 10)
Lounge.create(category_id: 11)
Lounge.create(category_id: 12)
Lounge.create(category_id: 13)
Lounge.create(category_id: 14)
Lounge.create(category_id: 15)
Lounge.create(category_id: 16)
Lounge.create(category_id: 17)